const STORE_KEY = 'transitOpsDataV2';
const emptyData = () => ({ vehicles: [], drivers: [], trips: [], maintenance: [], fuel: [], expenses: [], settings: {} });
const getData = () => { try { return { ...emptyData(), ...JSON.parse(localStorage.getItem(STORE_KEY) || '{}') }; } catch { return emptyData(); } };
const saveData = data => localStorage.setItem(STORE_KEY, JSON.stringify(data));
const id = () => `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const $ = selector => document.querySelector(selector);
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
const dateText = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : '—';
const statusClass = value => ({ Available:'green', 'On Trip':'blue', 'In Shop':'yellow', Retired:'red', 'Off Duty':'gray', Suspended:'red', Draft:'gray', Dispatched:'blue', Completed:'green', Cancelled:'red', Open:'yellow', Closed:'green' }[value] || 'gray');
const badge = value => `<span class="badge ${statusClass(value)}">${esc(value)}</span>`;
function showNotice(selector, message, error = false) { const el = $(selector); if (!el) return; el.textContent = message; el.className = `notice${error ? ' error' : ''}`; el.style.display = 'block'; setTimeout(() => { el.style.display = 'none'; }, 5000); }
function currentUser() { try { return JSON.parse(localStorage.getItem('user') || '{}'); } catch { return {}; } }
function setupHeader() { const user = currentUser(), role = user.role || 'Guest'; if (!user.role) { location.href = 'index.html'; return false; } document.querySelectorAll('#currentRole').forEach(el => { el.innerHTML = `Role: ${esc(role)} <span class="avatar">${esc(role.split(/\s|\//).map(x => x[0]).join('').slice(0,2) || 'T')}</span>`; }); return true; }
function setEmpty(tableId, emptyId, active) { const table = $(tableId)?.closest('table'); const empty = $(emptyId); if (table) table.style.display = active ? '' : 'none'; if (empty) empty.style.display = active ? 'none' : ''; }
function vehiclesById(data) { return Object.fromEntries(data.vehicles.map(v => [v.id, v])); }
function driversById(data) { return Object.fromEntries(data.drivers.map(d => [d.id, d])); }
function renderDashboard() { const data = getData(), activeVehicles = data.vehicles.filter(v => v.status !== 'Retired').length, available = data.vehicles.filter(v => v.status === 'Available').length, inShop = data.vehicles.filter(v => v.status === 'In Shop').length, activeTrips = data.trips.filter(t => t.status === 'Dispatched').length, pending = data.trips.filter(t => t.status === 'Draft').length, drivers = data.drivers.filter(d => d.status === 'On Trip').length, utilization = activeVehicles ? Math.round((data.vehicles.filter(v => v.status === 'On Trip').length / activeVehicles) * 100) : 0;
  $('#kpiActive').textContent = activeVehicles; $('#kpiAvailable').textContent = available; $('#kpiShop').textContent = inShop; $('#kpiActiveTrips').textContent = activeTrips; $('#kpiPendingTrips').textContent = pending; $('#kpiDrivers').textContent = drivers; $('#kpiUtilization').textContent = `${utilization}%`;
  const vs = vehiclesById(data), ds = driversById(data), trips = data.trips.slice().reverse().slice(0,6); $('#recentTrips').innerHTML = trips.map(t => `<tr><td>${esc(t.code)}</td><td>${esc(t.source)} → ${esc(t.destination)}</td><td>${esc(vs[t.vehicleId]?.name || '—')}</td><td>${esc(ds[t.driverId]?.name || '—')}</td><td>${badge(t.status)}</td></tr>`).join(''); $('#recentTripsEmpty').style.display = trips.length ? 'none' : '';
  const statuses = ['Available','On Trip','In Shop','Retired']; $('#vehicleStatus').innerHTML = statuses.map(s => { const n = data.vehicles.filter(v => v.status === s).length, p = data.vehicles.length ? Math.round(n / data.vehicles.length * 100) : 0; return `<div class="progress-row"><span>${s}</span><div class="bar"><i style="width:${p}%;--bar:${s==='Available'?'#25c55a':s==='On Trip'?'#55a6ed':s==='In Shop'?'#f2b520':'#f05151'}"></i></div><b>${n}</b></div>`; }).join(''); }
function renderVehicles() { const data = getData(), rows = data.vehicles; $('#vehicleRows').innerHTML = rows.map(v => `<tr><td>${esc(v.registration)}</td><td>${esc(v.name)}</td><td>${esc(v.type)}</td><td>${esc(v.capacity)} kg</td><td>${Number(v.odometer).toLocaleString()} km</td><td>${money(v.cost)}</td><td>${badge(v.status)}</td><td><div class="table-actions"><button class="secondary-btn" data-vehicle-edit="${v.id}">Edit</button><button class="danger-btn" data-vehicle-delete="${v.id}">Delete</button></div></td></tr>`).join(''); setEmpty('#vehicleRows','#vehicleEmpty',rows.length > 0); }
function resetVehicle() { $('#vehicleForm').reset(); $('#vehicleId').value = ''; $('#vehicleFormTitle').textContent = 'Register Vehicle'; $('#vehicleCancel').hidden = true; }
function setupVehicles() { renderVehicles(); $('#vehicleForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(), record = { id: $('#vehicleId').value || id(), registration: $('#registration').value.trim().toUpperCase(), name: $('#vehicleName').value.trim(), type: $('#vehicleType').value.trim(), capacity: Number($('#capacity').value), odometer: Number($('#odometer').value), cost: Number($('#acquisitionCost').value), status: $('#vehicleState').value }; if (data.vehicles.some(v => v.registration === record.registration && v.id !== record.id)) return showNotice('#vehicleNotice','Registration number must be unique.',true); const old = data.vehicles.find(v => v.id === record.id); if (old?.status === 'On Trip') return showNotice('#vehicleNotice','An On Trip vehicle cannot be edited.',true); if (old) Object.assign(old,record); else data.vehicles.push(record); saveData(data); resetVehicle(); renderVehicles(); showNotice('#vehicleNotice','Vehicle saved successfully.'); });
  $('#vehicleCancel').addEventListener('click',resetVehicle); document.addEventListener('click', e => { const edit = e.target.dataset.vehicleEdit, del = e.target.dataset.vehicleDelete; if (edit) { const v = getData().vehicles.find(x => x.id === edit); if (!v) return; if (v.status === 'On Trip') return showNotice('#vehicleNotice','Complete or cancel the trip before editing this vehicle.',true); $('#vehicleId').value=v.id; $('#registration').value=v.registration; $('#vehicleName').value=v.name; $('#vehicleType').value=v.type; $('#capacity').value=v.capacity; $('#odometer').value=v.odometer; $('#acquisitionCost').value=v.cost; $('#vehicleState').value=v.status; $('#vehicleFormTitle').textContent='Edit Vehicle'; $('#vehicleCancel').hidden=false; window.scrollTo({top:0,behavior:'smooth'}); } if (del) { const data=getData(), v=data.vehicles.find(x=>x.id===del); if (data.trips.some(t=>t.vehicleId===del&&t.status==='Dispatched') || data.maintenance.some(m=>m.vehicleId===del&&m.status==='Open')) return showNotice('#vehicleNotice','This vehicle has an active trip or maintenance log and cannot be deleted.',true); if (!confirm(`Delete ${v?.registration}?`)) return; data.vehicles=data.vehicles.filter(x=>x.id!==del); saveData(data); renderVehicles(); } }); }
function renderDrivers() { const data=getData(), rows=data.drivers; $('#driverRows').innerHTML=rows.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.license)}</td><td>${esc(d.category)}</td><td>${dateText(d.licenseExpiry)}</td><td>${esc(d.contact)}</td><td>${esc(d.safety)}%</td><td>${badge(d.status)}</td><td><div class="table-actions"><button class="secondary-btn" data-driver-edit="${d.id}">Edit</button><button class="danger-btn" data-driver-delete="${d.id}">Delete</button></div></td></tr>`).join(''); setEmpty('#driverRows','#driverEmpty',rows.length>0); }
function resetDriver(){ $('#driverForm').reset(); $('#driverId').value=''; $('#driverFormTitle').textContent='Add Driver'; $('#driverCancel').hidden=true; }
function setupDrivers(){ renderDrivers(); $('#driverForm').addEventListener('submit',e=>{e.preventDefault();const data=getData(),record={id:$('#driverId').value||id(),name:$('#driverName').value.trim(),license:$('#licenseNumber').value.trim().toUpperCase(),category:$('#licenseCategory').value.trim(),licenseExpiry:$('#licenseExpiry').value,contact:$('#driverContact').value.trim(),safety:Number($('#safetyScore').value),status:$('#driverState').value};if(data.drivers.some(d=>d.license===record.license&&d.id!==record.id))return showNotice('#driverNotice','License number must be unique.',true);const old=data.drivers.find(d=>d.id===record.id);if(old?.status==='On Trip')return showNotice('#driverNotice','An On Trip driver cannot be edited.',true);if(old)Object.assign(old,record);else data.drivers.push(record);saveData(data);resetDriver();renderDrivers();showNotice('#driverNotice','Driver saved successfully.');});$('#driverCancel').addEventListener('click',resetDriver);document.addEventListener('click',e=>{const edit=e.target.dataset.driverEdit,del=e.target.dataset.driverDelete;if(edit){const d=getData().drivers.find(x=>x.id===edit);if(d.status==='On Trip')return showNotice('#driverNotice','Complete or cancel the trip before editing this driver.',true);$('#driverId').value=d.id;$('#driverName').value=d.name;$('#licenseNumber').value=d.license;$('#licenseCategory').value=d.category;$('#licenseExpiry').value=d.licenseExpiry;$('#driverContact').value=d.contact;$('#safetyScore').value=d.safety;$('#driverState').value=d.status;$('#driverFormTitle').textContent='Edit Driver';$('#driverCancel').hidden=false;window.scrollTo({top:0,behavior:'smooth'});}if(del){const data=getData();if(data.trips.some(t=>t.driverId===del&&t.status==='Dispatched'))return showNotice('#driverNotice','This driver has an active trip and cannot be deleted.',true);if(!confirm('Delete this driver?'))return;data.drivers=data.drivers.filter(x=>x.id!==del);saveData(data);renderDrivers();}}); }
function setupSearch(){document.querySelectorAll('[data-search]').forEach(input=>input.addEventListener('input',()=>{const query=input.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(row=>{row.style.display=row.textContent.toLowerCase().includes(query)?'':'none';});}));}
function boot(){if(!setupHeader())return;setupSearch();const page=document.body.dataset.page;if(page==='dashboard')renderDashboard();if(page==='vehicles')setupVehicles();if(page==='drivers')setupDrivers();}
boot();
