const STORE_KEY = 'transitOpsDataV2';
const emptyData = () => ({ vehicles: [], drivers: [], trips: [], maintenance: [], fuel: [], expenses: [], settings: {} });
const getData = () => { try { return { ...emptyData(), ...JSON.parse(localStorage.getItem(STORE_KEY) || '{}') }; } catch { return emptyData(); } };
const saveData = data => localStorage.setItem(STORE_KEY, JSON.stringify(data));
const id = () => `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const $ = selector => document.querySelector(selector);
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const dateText = value => value ? new Date(`${value}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const statusClass = value => ({ Available: 'green', 'On Trip': 'blue', 'In Shop': 'yellow', Retired: 'red', 'Off Duty': 'gray', Suspended: 'red', Draft: 'gray', Dispatched: 'blue', Completed: 'green', Cancelled: 'red', Open: 'yellow', Closed: 'green' }[value] || 'gray');
const badge = value => `<span class="badge ${statusClass(value)}">${esc(value)}</span>`;
function showNotice(selector, message, error = false) { const el = $(selector); if (!el) return; el.textContent = message; el.className = `notice${error ? ' error' : ''}`; el.style.display = 'block'; setTimeout(() => { el.style.display = 'none'; }, 5000); }
function currentUser() { try { return JSON.parse(localStorage.getItem('user') || '{}'); } catch { return {}; } }
function setupHeader() { const user = currentUser(), role = user.role || 'Guest'; if (!user.role) { location.href = 'index.html'; return false; } document.querySelectorAll('#currentRole').forEach(el => { el.innerHTML = `Role: ${esc(role)} <span class="avatar">${esc(role.split(/\s|\//).map(x => x[0]).join('').slice(0, 2) || 'T')}</span>`; }); return true; }
function setEmpty(tableId, emptyId, active) { const table = $(tableId)?.closest('table'); const empty = $(emptyId); if (table) table.style.display = active ? '' : 'none'; if (empty) empty.style.display = active ? 'none' : ''; }
function vehiclesById(data) { return Object.fromEntries(data.vehicles.map(v => [v.id, v])); }
function driversById(data) { return Object.fromEntries(data.drivers.map(d => [d.id, d])); }
function renderDashboard() {
  const data = getData(), activeVehicles = data.vehicles.filter(v => v.status !== 'Retired').length, available = data.vehicles.filter(v => v.status === 'Available').length, inShop = data.vehicles.filter(v => v.status === 'In Shop').length, activeTrips = data.trips.filter(t => t.status === 'Dispatched').length, pending = data.trips.filter(t => t.status === 'Draft').length, drivers = data.drivers.filter(d => d.status === 'On Trip').length, utilization = activeVehicles ? Math.round((data.vehicles.filter(v => v.status === 'On Trip').length / activeVehicles) * 100) : 0;
  $('#kpiActive').textContent = activeVehicles; $('#kpiAvailable').textContent = available; $('#kpiShop').textContent = inShop; $('#kpiActiveTrips').textContent = activeTrips; $('#kpiPendingTrips').textContent = pending; $('#kpiDrivers').textContent = drivers; $('#kpiUtilization').textContent = `${utilization}%`;
  const today = new Date(), inThirtyDays = new Date(today); inThirtyDays.setDate(today.getDate() + 30); const dueLicenses = data.drivers.filter(d => { const expiry = new Date(`${d.licenseExpiry}T00:00:00`); return d.status === 'Suspended' || expiry < inThirtyDays; }); const readyPairs = Math.min(available, data.drivers.filter(validDriver).length); $('#readyResources').textContent = `${readyPairs} ready pair${readyPairs === 1 ? '' : 's'}`; $('#licenseWatch').textContent = `${dueLicenses.length} license alert${dueLicenses.length === 1 ? '' : 's'}`; $('#nextAction').textContent = readyPairs ? 'Ready to create a safe trip' : available ? 'Add a compliant driver' : 'Add an available vehicle';
  const vs = vehiclesById(data), ds = driversById(data), trips = data.trips.slice().reverse().slice(0, 6); $('#recentTrips').innerHTML = trips.map(t => `<tr><td>${esc(t.code)}</td><td>${esc(t.source)} → ${esc(t.destination)}</td><td>${esc(vs[t.vehicleId]?.name || '—')}</td><td>${esc(ds[t.driverId]?.name || '—')}</td><td>${badge(t.status)}</td></tr>`).join(''); $('#recentTripsEmpty').style.display = trips.length ? 'none' : '';
  const statuses = ['Available', 'On Trip', 'In Shop', 'Retired']; $('#vehicleStatus').innerHTML = statuses.map(s => { const n = data.vehicles.filter(v => v.status === s).length, p = data.vehicles.length ? Math.round(n / data.vehicles.length * 100) : 0; return `<div class="progress-row"><span>${s}</span><div class="bar"><i style="width:${p}%;--bar:${s === 'Available' ? '#25c55a' : s === 'On Trip' ? '#55a6ed' : s === 'In Shop' ? '#f2b520' : '#f05151'}"></i></div><b>${n}</b></div>`; }).join('');
}
function renderVehicles() { const data = getData(), rows = data.vehicles; $('#vehicleRows').innerHTML = rows.map(v => `<tr><td>${esc(v.registration)}</td><td>${esc(v.name)}</td><td>${esc(v.type)}</td><td>${esc(v.capacity)} kg</td><td>${Number(v.odometer).toLocaleString()} km</td><td>${money(v.cost)}</td><td>${badge(v.status)}</td><td><div class="table-actions"><button class="secondary-btn" data-vehicle-edit="${v.id}">Edit</button><button class="danger-btn" data-vehicle-delete="${v.id}">Delete</button></div></td></tr>`).join(''); setEmpty('#vehicleRows', '#vehicleEmpty', rows.length > 0); }
function resetVehicle() { $('#vehicleForm').reset(); $('#vehicleId').value = ''; $('#vehicleFormTitle').textContent = 'Register Vehicle'; $('#vehicleCancel').hidden = true; }
function setupVehicles() {
  renderVehicles(); $('#vehicleForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(), record = { id: $('#vehicleId').value || id(), registration: $('#registration').value.trim().toUpperCase(), name: $('#vehicleName').value.trim(), type: $('#vehicleType').value.trim(), capacity: Number($('#capacity').value), odometer: Number($('#odometer').value), cost: Number($('#acquisitionCost').value), status: $('#vehicleState').value }; if (data.vehicles.some(v => v.registration === record.registration && v.id !== record.id)) return showNotice('#vehicleNotice', 'Registration number must be unique.', true); const old = data.vehicles.find(v => v.id === record.id); if (old?.status === 'On Trip') return showNotice('#vehicleNotice', 'An On Trip vehicle cannot be edited.', true); if (old) Object.assign(old, record); else data.vehicles.push(record); saveData(data); resetVehicle(); renderVehicles(); showNotice('#vehicleNotice', 'Vehicle saved successfully.'); });
  $('#vehicleCancel').addEventListener('click', resetVehicle); document.addEventListener('click', e => { const edit = e.target.dataset.vehicleEdit, del = e.target.dataset.vehicleDelete; if (edit) { const v = getData().vehicles.find(x => x.id === edit); if (!v) return; if (v.status === 'On Trip') return showNotice('#vehicleNotice', 'Complete or cancel the trip before editing this vehicle.', true); $('#vehicleId').value = v.id; $('#registration').value = v.registration; $('#vehicleName').value = v.name; $('#vehicleType').value = v.type; $('#capacity').value = v.capacity; $('#odometer').value = v.odometer; $('#acquisitionCost').value = v.cost; $('#vehicleState').value = v.status; $('#vehicleFormTitle').textContent = 'Edit Vehicle'; $('#vehicleCancel').hidden = false; window.scrollTo({ top: 0, behavior: 'smooth' }); } if (del) { const data = getData(), v = data.vehicles.find(x => x.id === del); if (data.trips.some(t => t.vehicleId === del && t.status === 'Dispatched') || data.maintenance.some(m => m.vehicleId === del && m.status === 'Open')) return showNotice('#vehicleNotice', 'This vehicle has an active trip or maintenance log and cannot be deleted.', true); if (!confirm(`Delete ${v?.registration}?`)) return; data.vehicles = data.vehicles.filter(x => x.id !== del); saveData(data); renderVehicles(); } });
}
function renderDrivers() { const data = getData(), rows = data.drivers; $('#driverRows').innerHTML = rows.map(d => `<tr><td>${esc(d.name)}</td><td>${esc(d.license)}</td><td>${esc(d.category)}</td><td>${dateText(d.licenseExpiry)}</td><td>${esc(d.contact)}</td><td>${esc(d.safety)}%</td><td>${badge(d.status)}</td><td><div class="table-actions"><button class="secondary-btn" data-driver-edit="${d.id}">Edit</button><button class="danger-btn" data-driver-delete="${d.id}">Delete</button></div></td></tr>`).join(''); setEmpty('#driverRows', '#driverEmpty', rows.length > 0); }
function resetDriver() { $('#driverForm').reset(); $('#driverId').value = ''; $('#driverFormTitle').textContent = 'Add Driver'; $('#driverCancel').hidden = true; }
function setupDrivers() { renderDrivers(); $('#driverForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(), record = { id: $('#driverId').value || id(), name: $('#driverName').value.trim(), license: $('#licenseNumber').value.trim().toUpperCase(), category: $('#licenseCategory').value.trim(), licenseExpiry: $('#licenseExpiry').value, contact: $('#driverContact').value.trim(), safety: Number($('#safetyScore').value), status: $('#driverState').value }; if (data.drivers.some(d => d.license === record.license && d.id !== record.id)) return showNotice('#driverNotice', 'License number must be unique.', true); const old = data.drivers.find(d => d.id === record.id); if (old?.status === 'On Trip') return showNotice('#driverNotice', 'An On Trip driver cannot be edited.', true); if (old) Object.assign(old, record); else data.drivers.push(record); saveData(data); resetDriver(); renderDrivers(); showNotice('#driverNotice', 'Driver saved successfully.'); }); $('#driverCancel').addEventListener('click', resetDriver); document.addEventListener('click', e => { const edit = e.target.dataset.driverEdit, del = e.target.dataset.driverDelete; if (edit) { const d = getData().drivers.find(x => x.id === edit); if (d.status === 'On Trip') return showNotice('#driverNotice', 'Complete or cancel the trip before editing this driver.', true); $('#driverId').value = d.id; $('#driverName').value = d.name; $('#licenseNumber').value = d.license; $('#licenseCategory').value = d.category; $('#licenseExpiry').value = d.licenseExpiry; $('#driverContact').value = d.contact; $('#safetyScore').value = d.safety; $('#driverState').value = d.status; $('#driverFormTitle').textContent = 'Edit Driver'; $('#driverCancel').hidden = false; window.scrollTo({ top: 0, behavior: 'smooth' }); } if (del) { const data = getData(); if (data.trips.some(t => t.driverId === del && t.status === 'Dispatched')) return showNotice('#driverNotice', 'This driver has an active trip and cannot be deleted.', true); if (!confirm('Delete this driver?')) return; data.drivers = data.drivers.filter(x => x.id !== del); saveData(data); renderDrivers(); } }); }
function validDriver(driver) { return driver.status === 'Available' && driver.licenseExpiry >= new Date().toISOString().slice(0, 10); }
function fillTripOptions() { const data = getData(), vehicles = data.vehicles.filter(v => v.status === 'Available'), drivers = data.drivers.filter(validDriver); $('#tripVehicle').innerHTML = vehicles.length ? `<option value="">Select available vehicle</option>${vehicles.map(v => `<option value="${v.id}">${esc(v.registration)} · ${esc(v.name)} · ${v.capacity} kg</option>`).join('')}` : '<option value="">No available vehicles</option>'; $('#tripDriver').innerHTML = drivers.length ? `<option value="">Select compliant driver</option>${drivers.map(d => `<option value="${d.id}">${esc(d.name)} · ${esc(d.license)}</option>`).join('')}` : '<option value="">No compliant drivers</option>'; renderTripValidation(); }
function setTripRule(id, state, label) { const rule = $(id); if (!rule) return; rule.className = `rule-check ${state}`; rule.querySelector('.rule-icon').textContent = state === 'pass' ? '✓' : state === 'fail' ? '!' : '○'; rule.querySelector('b').textContent = label; }
function renderTripValidation() { const data = getData(), vehicle = data.vehicles.find(v => v.id === $('#tripVehicle')?.value), driver = data.drivers.find(d => d.id === $('#tripDriver')?.value), cargo = Number($('#tripCargo')?.value || 0); const vehiclePass = vehicle?.status === 'Available', driverPass = driver?.status === 'Available', licensePass = Boolean(driver) && validDriver(driver); setTripRule('#vehicleRule', vehicle ? (vehiclePass ? 'pass' : 'fail') : 'waiting', vehicle ? (vehiclePass ? 'Pass' : 'Blocked') : 'Waiting'); setTripRule('#driverRule', driver ? (driverPass ? 'pass' : 'fail') : 'waiting', driver ? (driverPass ? 'Pass' : 'Blocked') : 'Waiting'); setTripRule('#licenseRule', driver ? (licensePass ? 'pass' : 'fail') : 'waiting', driver ? (licensePass ? 'Pass' : 'Expired') : 'Waiting'); const cargoText = $('#cargoRuleText'); if (!vehicle || !cargo) { if (cargoText) cargoText.textContent = 'Enter cargo weight to check capacity.'; setTripRule('#cargoRule', 'waiting', 'Waiting'); } else { const fits = cargo <= vehicle.capacity; if (cargoText) cargoText.textContent = `${cargo} kg cargo / ${vehicle.capacity} kg maximum capacity.`; setTripRule('#cargoRule', fits ? 'pass' : 'fail', fits ? 'Pass' : 'Over limit'); } }
function renderTrips() { const data = getData(), vs = vehiclesById(data), ds = driversById(data), rows = data.trips.slice().reverse(); $('#tripRows').innerHTML = rows.map(t => `<tr><td>${esc(t.code)}</td><td>${esc(t.source)} → ${esc(t.destination)}</td><td>${esc(vs[t.vehicleId]?.registration || 'Deleted')}</td><td>${esc(ds[t.driverId]?.name || 'Deleted')}</td><td>${t.cargo} kg</td><td>${t.distance} km</td><td>${badge(t.status)}</td><td><div class="table-actions">${t.status === 'Draft' ? `<button class="small-btn" data-trip-dispatch="${t.id}">Dispatch</button><button class="danger-btn" data-trip-cancel="${t.id}">Delete</button>` : ''}${t.status === 'Dispatched' ? `<button class="small-btn" data-trip-complete="${t.id}">Complete</button><button class="danger-btn" data-trip-cancel="${t.id}">Cancel</button>` : ''}</div></td></tr>`).join(''); setEmpty('#tripRows', '#tripEmpty', rows.length > 0); }
function createTrip(dispatch) { const data = getData(), vehicle = data.vehicles.find(v => v.id === $('#tripVehicle').value), driver = data.drivers.find(d => d.id === $('#tripDriver').value), cargo = Number($('#tripCargo').value); if (!vehicle || !driver) return showNotice('#tripNotice', 'Select an available vehicle and a compliant driver.', true); if (cargo > vehicle.capacity) return showNotice('#tripNotice', `Cargo weight cannot exceed ${vehicle.capacity} kg.`, true); if (dispatch && (!validDriver(driver) || vehicle.status !== 'Available')) return showNotice('#tripNotice', 'Selected vehicle or driver is no longer eligible for dispatch.', true); const trip = { id: id(), code: `TRP-${String(data.trips.length + 1).padStart(4, '0')}`, source: $('#tripSource').value.trim(), destination: $('#tripDestination').value.trim(), vehicleId: vehicle.id, driverId: driver.id, cargo, distance: Number($('#tripDistance').value), status: dispatch ? 'Dispatched' : 'Draft', createdAt: new Date().toISOString() }; data.trips.push(trip); if (dispatch) { vehicle.status = 'On Trip'; driver.status = 'On Trip'; } saveData(data); $('#tripForm').reset(); fillTripOptions(); renderTrips(); showNotice('#tripNotice', dispatch ? 'Trip dispatched. Vehicle and driver are now On Trip.' : 'Trip saved as Draft.'); }
function transitionTrip(tripId, action) { const data = getData(), trip = data.trips.find(t => t.id === tripId); if (!trip) return; const vehicle = data.vehicles.find(x => x.id === trip.vehicleId), driver = data.drivers.find(x => x.id === trip.driverId); if (action === 'dispatch') { if (!vehicle || !driver || vehicle.status !== 'Available' || !validDriver(driver)) return alert('This trip cannot be dispatched because its vehicle or driver is unavailable.'); if (trip.cargo > vehicle.capacity) return alert('Cargo weight exceeds vehicle capacity.'); trip.status = 'Dispatched'; vehicle.status = 'On Trip'; driver.status = 'On Trip'; } else { trip.status = action === 'complete' ? 'Completed' : 'Cancelled'; if (vehicle?.status === 'On Trip') vehicle.status = 'Available'; if (driver?.status === 'On Trip') driver.status = 'Available'; } saveData(data); fillTripOptions(); renderTrips(); }
function setupTrips() { fillTripOptions(); renderTrips(); ['#tripVehicle', '#tripDriver', '#tripCargo'].forEach(selector => $(selector).addEventListener('input', renderTripValidation)); $('#tripForm').addEventListener('submit', e => { e.preventDefault(); createTrip(true); }); $('#saveDraft').addEventListener('click', () => { if (!$('#tripForm').reportValidity()) return; createTrip(false); }); document.addEventListener('click', e => { if (e.target.dataset.tripDispatch) transitionTrip(e.target.dataset.tripDispatch, 'dispatch'); if (e.target.dataset.tripComplete) transitionTrip(e.target.dataset.tripComplete, 'complete'); if (e.target.dataset.tripCancel) { const data = getData(), trip = data.trips.find(t => t.id === e.target.dataset.tripCancel); if (!trip) return; if (trip.status === 'Draft') { data.trips = data.trips.filter(t => t.id !== trip.id); saveData(data); renderTrips(); } else if (confirm('Cancel this dispatched trip?')) transitionTrip(trip.id, 'cancel'); } }); }
function fillVehicleSelect(selector, availableOnly = false) { const data = getData(), list = data.vehicles.filter(v => availableOnly ? v.status === 'Available' : v.status !== 'Retired'); $(selector).innerHTML = list.length ? `<option value="">Select vehicle</option>${list.map(v => `<option value="${v.id}">${esc(v.registration)} · ${esc(v.name)}</option>`).join('')}` : '<option value="">Add a vehicle first</option>'; }
function renderMaintenance() { const data = getData(), vs = vehiclesById(data), rows = data.maintenance.slice().reverse(); $('#maintenanceRows').innerHTML = rows.map(m => `<tr><td>${esc(vs[m.vehicleId]?.registration || 'Deleted')}</td><td>${esc(m.type)}</td><td>${dateText(m.date)}</td><td>${money(m.cost)}</td><td>${badge(m.status)}</td><td>${m.status === 'Open' ? `<button class="small-btn" data-maintenance-close="${m.id}">Close log</button>` : '—'}</td></tr>`).join(''); setEmpty('#maintenanceRows', '#maintenanceEmpty', rows.length > 0); }
function setupMaintenance() { fillVehicleSelect('#maintenanceVehicle', true); renderMaintenance(); $('#maintenanceForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(), vehicle = data.vehicles.find(v => v.id === $('#maintenanceVehicle').value); if (!vehicle || vehicle.status !== 'Available') return showNotice('#maintenanceNotice', 'Select an Available vehicle.', true); data.maintenance.push({ id: id(), vehicleId: vehicle.id, type: $('#maintenanceType').value.trim(), date: $('#maintenanceDate').value, cost: Number($('#maintenanceCost').value), notes: $('#maintenanceNotes').value.trim(), status: 'Open' }); vehicle.status = 'In Shop'; saveData(data); $('#maintenanceForm').reset(); fillVehicleSelect('#maintenanceVehicle', true); renderMaintenance(); showNotice('#maintenanceNotice', 'Maintenance log opened. Vehicle is now In Shop.'); }); document.addEventListener('click', e => { const maintenanceId = e.target.dataset.maintenanceClose; if (!maintenanceId) return; const data = getData(), log = data.maintenance.find(x => x.id === maintenanceId), vehicle = data.vehicles.find(x => x.id === log?.vehicleId); if (!log) return; log.status = 'Closed'; if (vehicle?.status === 'In Shop') vehicle.status = 'Available'; saveData(data); fillVehicleSelect('#maintenanceVehicle', true); renderMaintenance(); }); }
function renderExpenses() { const data = getData(), vs = vehiclesById(data), records = [...data.fuel.map(x => ({ ...x, kind: 'Fuel' })), ...data.expenses.map(x => ({ ...x, kind: x.type }))].sort((a, b) => b.date.localeCompare(a.date)); $('#expenseRows').innerHTML = records.map(x => `<tr><td>${esc(x.kind)}</td><td>${esc(vs[x.vehicleId]?.registration || 'Deleted')}</td><td>${dateText(x.date)}</td><td>${x.liters ? `${x.liters} L` : '—'}</td><td>${money(x.cost)}</td><td><button class="danger-btn" data-cost-delete="${x.kind === 'Fuel' ? 'fuel' : 'expense'}:${x.id}">Delete</button></td></tr>`).join(''); setEmpty('#expenseRows', '#expenseEmpty', records.length > 0); }
function setupFuel() { fillVehicleSelect('#fuelVehicle'); fillVehicleSelect('#expenseVehicle'); renderExpenses(); $('#fuelForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(); if (!$('#fuelVehicle').value) return showNotice('#fuelNotice', 'Select a vehicle first.', true); data.fuel.push({ id: id(), vehicleId: $('#fuelVehicle').value, date: $('#fuelDate').value, liters: Number($('#fuelLiters').value), cost: Number($('#fuelCost').value) }); saveData(data); $('#fuelForm').reset(); renderExpenses(); showNotice('#fuelNotice', 'Fuel log saved.'); }); $('#expenseForm').addEventListener('submit', e => { e.preventDefault(); const data = getData(); if (!$('#expenseVehicle').value) return showNotice('#expenseNotice', 'Select a vehicle first.', true); data.expenses.push({ id: id(), vehicleId: $('#expenseVehicle').value, date: $('#expenseDate').value, type: $('#expenseType').value, cost: Number($('#expenseCost').value) }); saveData(data); $('#expenseForm').reset(); renderExpenses(); showNotice('#expenseNotice', 'Expense saved.'); }); document.addEventListener('click', e => { const ref = e.target.dataset.costDelete; if (!ref) return; const [type, recordId] = ref.split(':'); const data = getData(); data[type === 'fuel' ? 'fuel' : 'expenses'] = data[type === 'fuel' ? 'fuel' : 'expenses'].filter(x => x.id !== recordId); saveData(data); renderExpenses(); }); }
function reportData() { const data = getData(); return data.vehicles.map(vehicle => { const fuel = data.fuel.filter(x => x.vehicleId === vehicle.id), maintenance = data.maintenance.filter(x => x.vehicleId === vehicle.id), expenses = data.expenses.filter(x => x.vehicleId === vehicle.id), trips = data.trips.filter(x => x.vehicleId === vehicle.id && x.status === 'Completed'); const fuelCost = fuel.reduce((sum, x) => sum + x.cost, 0), maintenanceCost = maintenance.reduce((sum, x) => sum + x.cost, 0), otherCost = expenses.reduce((sum, x) => sum + x.cost, 0), liters = fuel.reduce((sum, x) => sum + x.liters, 0), distance = trips.reduce((sum, x) => sum + x.distance, 0), cost = fuelCost + maintenanceCost + otherCost, roi = vehicle.cost ? -cost / vehicle.cost * 100 : 0; return { vehicle, fuelCost, maintenanceCost, otherCost, liters, distance, cost, roi }; }); }
function renderAnalytics() { const rows = reportData(), totalCost = rows.reduce((sum, x) => sum + x.cost, 0), totalFuel = rows.reduce((sum, x) => sum + x.liters, 0), totalDistance = rows.reduce((sum, x) => sum + x.distance, 0), totalVehicles = rows.length, onTrip = rows.filter(x => x.vehicle.status === 'On Trip').length; $('#reportCost').textContent = money(totalCost); $('#reportEfficiency').textContent = totalFuel ? `${(totalDistance / totalFuel).toFixed(2)} km/L` : '—'; $('#reportUtilization').textContent = totalVehicles ? `${Math.round(onTrip / totalVehicles * 100)}%` : '0%'; $('#reportDistance').textContent = `${totalDistance} km`; $('#reportFuel').textContent = `${totalFuel} L`; $('#reportRoi').textContent = rows.length ? `${(rows.reduce((sum, x) => sum + x.roi, 0) / rows.length).toFixed(2)}%` : '—'; $('#reportRows').innerHTML = rows.map(x => `<tr><td>${esc(x.vehicle.registration)} · ${esc(x.vehicle.name)}</td><td>${money(x.fuelCost)}</td><td>${money(x.maintenanceCost)}</td><td>${money(x.otherCost)}</td><td>${money(x.cost)}</td><td>${x.liters ? `${(x.distance / x.liters).toFixed(2)} km/L` : '—'}</td><td>${x.roi.toFixed(2)}%</td></tr>`).join(''); setEmpty('#reportRows', '#reportEmpty', rows.length > 0); }
function exportCsv() { const rows = reportData(), header = ['Registration', 'Vehicle', 'Fuel Cost', 'Maintenance Cost', 'Other Expense', 'Operational Cost', 'Fuel Efficiency', 'ROI'], values = rows.map(x => [x.vehicle.registration, x.vehicle.name, x.fuelCost, x.maintenanceCost, x.otherCost, x.cost, x.liters ? (x.distance / x.liters).toFixed(2) : '', x.roi.toFixed(2)]), csv = [header, ...values].map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n'), blob = new Blob([csv], { type: 'text/csv' }), url = URL.createObjectURL(blob), anchor = document.createElement('a'); anchor.href = url; anchor.download = 'transitops-report.csv'; anchor.click(); URL.revokeObjectURL(url); }
function setupAnalytics() { renderAnalytics(); $('#exportCsv').addEventListener('click', exportCsv); }
function setupSettings() { const data = getData(), settings = data.settings || {}; $('#organizationName').value = settings.organizationName || ''; $('#timezone').value = settings.timezone || 'Asia/Kolkata'; $('#language').value = settings.language || 'English'; $('#settingsForm').addEventListener('submit', e => { e.preventDefault(); const latest = getData(); latest.settings = { organizationName: $('#organizationName').value.trim(), timezone: $('#timezone').value, language: $('#language').value }; saveData(latest); showNotice('#settingsNotice', 'Settings saved.'); }); }
function setupSearch() { document.querySelectorAll('[data-search]').forEach(input => input.addEventListener('input', () => { const query = input.value.toLowerCase(); document.querySelectorAll('tbody tr').forEach(row => { row.style.display = row.textContent.toLowerCase().includes(query) ? '' : 'none'; }); })); }
function boot() { if (!setupHeader()) return; setupSearch(); const page = document.body.dataset.page; if (page === 'dashboard') renderDashboard(); if (page === 'vehicles') setupVehicles(); if (page === 'drivers') setupDrivers(); if (page === 'trips') setupTrips(); if (page === 'maintenance') setupMaintenance(); if (page === 'fuel') setupFuel(); if (page === 'analytics') setupAnalytics(); if (page === 'settings') setupSettings(); }
boot();
