"""create vehicles and drivers tables

Revision ID: d637f1379e00
Revises: aaea2ffdd897
Create Date: 2026-07-12 14:27:04.559782

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d637f1379e00"
down_revision: str | Sequence[str] | None = "aaea2ffdd897"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_code", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=False),
        sa.Column("licence_number", sa.String(length=50), nullable=False),
        sa.Column("licence_category", sa.String(length=50), nullable=False),
        sa.Column("licence_expiry_date", sa.Date(), nullable=False),
        sa.Column("joining_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "on_trip",
                "suspended",
                "inactive",
                name="driver_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drivers")),
        sa.UniqueConstraint("email", name=op.f("uq_drivers_email")),
        sa.UniqueConstraint("employee_code", name=op.f("uq_drivers_employee_code")),
        sa.UniqueConstraint("licence_number", name=op.f("uq_drivers_licence_number")),
    )
    op.create_index(
        op.f("ix_drivers_licence_expiry_date"),
        "drivers",
        ["licence_expiry_date"],
        unique=False,
    )
    op.create_index(op.f("ix_drivers_status"), "drivers", ["status"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("registration_number", sa.String(length=30), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum(
                "truck",
                "van",
                "trailer",
                "pickup",
                "other",
                name="vehicle_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("manufacturing_year", sa.SmallInteger(), nullable=False),
        sa.Column("capacity_kg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "odometer_km",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0.00"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "available",
                "on_trip",
                "in_shop",
                "retired",
                name="vehicle_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="available",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("capacity_kg > 0", name="ck_vehicles_capacity_positive"),
        sa.CheckConstraint(
            "manufacturing_year >= 1980", name="ck_vehicles_manufacturing_year"
        ),
        sa.CheckConstraint(
            "odometer_km >= 0", name="ck_vehicles_odometer_non_negative"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
        sa.UniqueConstraint(
            "registration_number", name=op.f("uq_vehicles_registration_number")
        ),
    )
    op.create_index(op.f("ix_vehicles_status"), "vehicles", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicles_status"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_drivers_status"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_licence_expiry_date"), table_name="drivers")
    op.drop_table("drivers")
    # ### end Alembic commands ###
